[terminal]
shell = {program = "wsl.exe", args = ["--", "zsh", "-l"]}

[general]
import = [ "/mnt/c/Users/CarterSteele/AppData/Roaming/alacritty/alacritty-theme/themes/acme.toml"]
working_directory = "\\\\wsl$\\ubuntubackup\\home\\jaime"


[window]
startup_mode = "Maximized"
decorations = "None"
decorations_theme_variant = "Dark"
padding = { x = 10, y = 10 }

[font]
normal = {family = "3270 Nerd Font"}
size = 12
